Document: invesalius
Title: Debian invesalius Manual
Author: <insert document author here>
Abstract: This manual describes what invesalius is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/invesalius/invesalius.sgml.gz

Format: postscript
Files: /usr/share/doc/invesalius/invesalius.ps.gz

Format: text
Files: /usr/share/doc/invesalius/invesalius.text.gz

Format: HTML
Index: /usr/share/doc/invesalius/html/index.html
Files: /usr/share/doc/invesalius/html/*.html
